import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Open_Sans } from "next/font/google";
import Footer from "@/components/Footer";
import SplashProvider from "./splash-provider";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans`}>
        <SplashProvider>
          <Navbar />
          {children}
          <Footer />
        </SplashProvider>
      </body>
    </html>
  );
}
